name: Build with cargo-equip and release

on:
  push:
    tags:
      - "v*.*.*"
      - "*-v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0 # Fetch all history to possibly update tags

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-equip
        run: cargo install cargo-equip --locked || true

      - name: Determine release variables
        id: release_vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=nightly" >> "$GITHUB_OUTPUT"
            echo "PRERELEASE=true" >> "$GITHUB_OUTPUT"
            echo "REL_NAME=Nightly $(date -u +'%Y-%m-%dT%H:%MZ')" >> "$GITHUB_OUTPUT"
          else
            echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
            echo "PRERELEASE=false" >> "$GITHUB_OUTPUT"
            echo "REL_NAME=Release ${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create or update nightly tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          set -euo pipefail
          git config user.name "statiolake"
          git config user.email "statiolake@gmail.com"
          git tag -f nightly
          git push origin refs/tags/nightly --force

      - name: Run cargo equip
        run: |
          set -euo pipefail
          mkdir -p build
          cargo equip --remove docs --remove comments --minify all > build/equip.raw.rs

      - name: Transform output
        run: |
          set -euo pipefail
          if ! grep -q '#\[allow(unused)\]' build/equip.raw.rs; then
            echo "ERROR: Marker '#[allow(unused)]' not found in cargo-equip output." >&2
            exit 1
          fi

          # Replace __cargo_equip → proconio_bundled
          sed "s/__cargo_equip/proconio_bundled/g" build/equip.raw.rs > build/equip.replaced.rs

          # Replace proconio_bundled_macro_def_proconio_* -> *
          sed -i "s/proconio_bundled_macro_def_proconio_//g" build/equip.replaced.rs

          # Keep from first #[allow(unused)] to the end
          sed -n '/#\[allow(unused)\]/,$p' build/equip.replaced.rs > build/proconio_bundled.rs

          echo "Final file at build/proconio_bundled.rs"
          wc -l build/proconio_bundled.rs

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: ${{ steps.release_vars.outputs.TAG }}
          name: ${{ steps.release_vars.outputs.REL_NAME }}
          body: |
            ⚠️ **Experimental Warning**: The bundled version (proconio_bundled.rs) is experimental and not tested. It may not work correctly in all environments. Using the bundled version may cause CE or RE that would not occur with the regular crate version. Please use with caution.
          draft: false
          prerelease: ${{ steps.release_vars.outputs.PRERELEASE }}
          files: |
            build/proconio_bundled.rs
